### PR TITLE
Adjustments fix

### PR DESCRIPTION
**Pull request by stephenhmarsh**
@cbartlett @ilanaseid 

* Fixes a long-standing issue in Spree around returning items on orders with discounts/order adjustments, especially if there is also sales tax.
* Documentation: https://docs.google.com/a/theline.com/document/d/1EVDXRgStUBOxjylNtnqTQMVNQsHhoUvpqpfpaciIZnw/edit?usp=sharing

### CODE REVIEW

**Comment by stephenhmarsh** [comment]
@cbartlett or @ilanaseid -- can we merge and launch this today so i can get docs out to retail and ops teams? thanks

**Comment by cbartlett** [comment]
@stephenhmarsh My only issue is the commented code here in `reimbursement_tax_caculator.rb`. Can we remove that? Makes me twitch. :sweat: 

Once this is merged, we have to update `theline` to point to the new version, right? Does that mean we have to bump the version in the `gemspec`?

And just to confirm the obvious: These haven't already been fixed in Spree itself have they? Seem like obvious issues. Should we be submitting PRs for these? This is a larger conversation for another time.

**Comment by stephenhmarsh** [comment]
@cbartlett 
sometimes SOME things are fixed in Spree, for sure, but often insufficiently or in stupid ways, and often break something else.   they have no quality control.  joel and i opened many issues with them... then one day, for better or worse, joel just decided to fork it and not look back.

i still cherry-pick something that seems relevant enough  or is security related.  but the real reason I didn't look towards their work for this particular issue is that Joel hacked returns fairly significantly, so i knew anything their community had released to make this better would've likely been incompatible with what we're doing.

i can remove the code comments but i really only make them for other people's benefit when i've encountered something complex to hopefully save them from duplicating that work.

to answer your q, good news is you do not need to alter the gemspec in any way, the line app will always point to the most recent commit of the branch when you bundle, same for CMS. it's all handled through the gemfile.lock ...   

when i work on these projects locally (CMS, Spree) i am using bundler local overrides to autoload all changes in

**Comment by stephenhmarsh** [comment]
@cbartlett -- re: "commented code" -- my b, i see what you mean now / that "commented code" ``!=`` "code comments"

**Comment by cbartlett** [comment]
Yep, I meant the commented code which is what git is for. I'm on a relentless pursuit to purge all that from our repo. Thanks for removing it.

Generally speaking, code comments are used for two things: to relay *what* code does and *why* it does it. Needing to relay *what* code does is a smell. A better design with smaller methods, and better method names along with an OO design can often solve that.

For *why*, I often advocate relying on small, atomic git commits with succinct messages, but there are still opaque reasons you want to annotate inline. And I'm okay with that, I have left those untouched so far. I'm pleased that we are commenting more for *why* and less for *what*.

**Pull request merged**
